CREATE TABLE users (
  id CHAR(36) PRIMARY KEY,
  nama VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE jadwal_kuliah (
  id SERIAL PRIMARY KEY,
  user_id CHAR(36) REFERENCES users(id),
  nama_mata_kuliah VARCHAR(255) NOT NULL,
  waktu_mulai TIME NOT NULL,
  waktu_selesai TIME NOT NULL,
  hari VARCHAR(255) NOT NULL,
  ruangan VARCHAR(255),
  catatan TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE tugas (
  id SERIAL PRIMARY KEY,
  user_id CHAR(36) REFERENCES users(id),
  judul VARCHAR(255) NOT NULL,
  deskripsi TEXT,
  deadline TIMESTAMP NOT NULL,
  status VARCHAR(255) NOT NULL,
  tipe VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE kelompok_tugas (
  id SERIAL PRIMARY KEY,
  tugas_id INTEGER REFERENCES tugas(id),
  nama_kelompok VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE anggota_kelompok (
  id SERIAL PRIMARY KEY,
  user_id CHAR(36) REFERENCES users(id),
  group_id INTEGER REFERENCES kelompok_tugas(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE catatan_progres (
  id SERIAL PRIMARY KEY,
  tugas_id INTEGER REFERENCES tugas(id),
  catatan TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE diskusi_tugas (
  id SERIAL PRIMARY KEY,
  group_id INTEGER REFERENCES kelompok_tugas(id),
  user_id CHAR(36) REFERENCES users(id),
  pesan TEXT NOT NULL,
  attachment TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
